name = "TheWorld"
author = "Korgix"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "377cf2d9d250fc3e99f1397598a3cf639fa290afb52d71102c673a1dc8a6e429"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
