name = "TheWorld"
author = "Korgix"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "501bb7d47c1d64ed8554d51819eeb702b54920bacebf39c30ac729112594ae0c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
