name = "TheWorld"
author = "Korgix"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "85a7fc04de8c5033b6e48941d4c1053e6a01a9d20e191c65666de36b2385b9c1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
